---
title: "Mitől függnek a fizetések? - Lineáris regresszió"
date: "10/05/2020"
output: html_document
---

A cél feltérképezni lineáris regresszióval, hogy milyen tényezőktől függnek a fizetések egy vállalatnál.

Adatfájl: *employee.RData* \
Forrás: IBM SPSS adatfájl \
Jelleg: keresztmetszeti \
Megfigyelések: 473 munkavállaló \
\
Numerikus változók:

 * *salary*: éves fizetés (ezer USD),
 * *age*: életkor (év), 
 * *educ*: iskolázottság (év),
 * *jobtime*: mióta dolgozik a cégnél (hónap),
 * *prevexp*: korábbi munkatapasztalat (hónap).

Kategorikus változók:

 * *gender* (nominális): nem (Female/Male),
 * *jobcat* (nominális): munkakör (Clerical/Custodial/Manager),
 * *minority* (nominális): kisebbségi származás (No/Yes).

**1. feladat**

Hajtsa végre az alábbiak modellezési lépéseket!

 a. Töltse be az adatfájlt, valamint a *car*, *HH*, *lmtest* és *sandwich* kiegészítő csomagokat!
 b. Építsen lineáris regressziós modellt, amely a fizetés logaritmusát minden lehetséges prediktor segítségével magyarázza!
 c. Szűrje új táblába, és nézze meg a kilógó egyéneket!
 d. Becsülje újra a modellt, és vizsgálja meg a multikollinearitást!
 e. Lehet-e ebben a példában probléma a hibatagok nemnormalitása? Vizsgálja meg ábrákon a feltevés teljesülését!
 f. Tesztelje a heteroszkedaszticitást! Probléma esetén a továbbiakban járjon el megfelelő módon!
 g. Vizsgálja meg és szükség esetén kezelje a nemlinearitást!
 h. Amennyiben vannak felesleges prediktorok a modellben, távolítsa el azokat!
 
------------------------------------------------

**2. feladat**

Értelmezze az 1. feladat végén kapott modellt az alábbiak szerint!

 a. Hogyan értelmezhető a prediktorok parciális hatása?
 b. Melyek a legfontosabb prediktorok?
 c. Minősítse a modell teljesítményét!
 d. Korreláció vagy ok-okozati kapcsolat áll fenn az egyes prediktorok és a fizetések között?

