---
title: "Adósminősítő rendszer építése - Logit modell"
date: "10/05/2020"
output: html_document
---

A cél: banki adósminősítő modell készítése.

Adatfájl: *bankloan.RData* \
Forrás: IBM SPSS adatfájl \
Jelleg: keresztmetszeti \
Megfigyelések: 700 adós \
\
Numerikus változók:

 * *age*: életkor (év), 
 * *employ*: munkaviszony hossza (év), 
 * *address*: mióta lakik a jelenlegi lakcímén (év), 
 * *debtinc*: összes adósság az éves jövedelem %-ában, 
 * *lincome*: éves jövedelem (ezer USD) logaritmusa,
 * *lcreddebt*: hitelkártya-adósság (ezer USD) logaritmusa,
 * *lothdebt*: egyéb adósság (ezer USD) logaritmusa.

Kategorikus változók:

 * *ed* (ordinális): iskolázottság (5 kategória),
 * *default* (nominális): fizetésképtelenség (No/Yes).

**1. feladat**

Hajtsa végre az alábbi modellezési lépéseket!

 a. Töltse be az adatfájlt, valamint a *car*, *HH*, *lmtest* és *sandwich* kiegészítő csomagokat!
 b. Építsen logit modellt, amely a fizetésképtelenséget minden lehetséges prediktor segítségével magyarázza!
 c. Szűrje új táblába, és nézze meg a kilógó egyéneket!
 d. Becsülje újra a modellt, és vizsgálja meg a multikollinearitást!
 e. Vizsgálja meg, és szükség esetén kezelje a nemlinearitást!
 f. Amennyiben vannak felesleges prediktorok a modellben, távolítsa el azokat!
 
----------------------


**2. feladat**

Értelmezze az 1. feladat végén kapott modellt az alábbiak szerint!

 a. Hogyan értelmezhető a prediktorok parciális hatása?
 b. Melyek a legfontosabb prediktorok?
 c. Minősítse a modell teljesítményét!
 d. Határozza meg az optimális küszöbértéket abban az esetben, ha a másodfajú hiba ötször költségesebb az elsőfajú hibánál!

------------------------------------









